services:
  - type: web
    name: chorgie-web
    env: static
    buildCommand: cd web && npm ci && npm run build
    staticPublishPath: ./web/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: chorgie-api
    env: node
    buildCommand: cd api && npm ci && npm run build
    startCommand: cd api && npm run start
    healthCheckPath: /health
